### ISSUE TITLE
勉強会

### ISSUE THREAD

**Issue by hirainra** [NoriakiHirai/Study#2]
https://techplay.jp/event/661995

**Comment by hirainra** [comment]
### 参加候補
2018/04/26 (木) 13:00 開催データを中心に据えたクラウドサービスとその価値
について考える 住　所：東京都千代田区 外神田 4-14-1
申込先：connpass


2018/04/26 (木) 19:00 開催外資系コンサルティングファーム出身者が実践する
AI×IoT時代のデジタル戦略立案を知る2時間半 住　所：東京都新宿区四谷2-12-5 
四谷ISYビル
申込先：TECH PLAY


2018/05/12 (土) 13:00 開催IGDA日本 ゲームサーバ勉強会 #8 住　所：東京都
渋谷区宇田川町20-17 NMF渋谷公園通りビル 8F
申込先：TECH PLAY


2018/06/16 (土) 10:30 開催企画担当者のためのリーン・アジャイル・プロダク
トマネジメント集中特訓講座 ～課題発見からバックログ作成へ～ #2 [東京日本
橋開催][POStudy Day][2018/06/16(土)] 住　所：〒103-6028 東京都中央区日本
橋2-7-1 (東京日本橋タワー 27F サイボウズ株式会社 カンファレンスルーム)
申込先：Doorkeeper


2018/06/05 (火) 15:00 開催技術セミナー「Delphi /C++Builder +FireDACで実
現するつながるシステムの開発」アプリケーションの接続性を高め、システムの
利便性を向上させよう！ 住　所：東京都文京区後楽2-3-21　住友不動産飯田橋
ビル 5F
申込先：ATND


2018/05/19 (土) 16:00 開催02東京：UIデザインの常識を改める「認知学から学
ぶUIの基本」 住　所：東京都千代田区内神田3-24-5 エッサム神田ホール 2号館
申込先：ストアカ


2018/05/20 (日) 17:30 開催04東京：ユーザーニーズにちゃんと応える「伝わる
UIデザイン」の妙 住　所：東京都千代田区内神田３－２４－５ エッサム神田ホ
ール２号館
申込先：ストアカ


2018/04/28 (土) 10:00 開催【拡大版】サーバー構築ハンズオン in 東京 #085 
住　所：東京都渋谷区恵比寿1-18-5 アルカサル恵比寿201
申込先：connpass


2018/04/29 (日) 17:00 開催【CEO登壇!】テクノロジーに仕事を奪われないため
のキャリア戦略 住　所：渋谷校 東京都渋谷区道玄坂2丁目10番12号 (新大宗ビ
ル3号館8階)
申込先：connpass


2018/05/06 (日) 13:00 開催William E. Byrd氏の東京講演 (TBD) 住　所：東京
都中央区築地１丁目１３−１ ＡＤＫ松竹スクエア
申込先：connpass


2018/04/24 (火) 15:00 開催孫正義が語る未来戦略と求められる人材 - ソフト
バンクキャリアLIVE - 住　所：〒100-0005 東京都千代田区丸の内３丁目５−１
申込先：その他         新着イベント


2018/04/19 (木) 19:00 開催X-Tech JAWS 【第3回】 住　所：〒100-0006 東京
都千代田区有楽町1-12-1 新有楽町ビル7F
申込先：Doorkeeper


2018/04/10 (火) 16:30 開催Djangoハンズオン: クラウドIDE(PaizaCloud)でWeb
サービスを作る 住　所：東京都港区南青山2-12-16 石塚商事ビル6F
申込先：connpass


2018/04/27 (金) 19:00 開催UI Crunch #13 娯楽のUI - by Nintendo - 住　所：
東京都渋谷区渋谷2-21-1 渋谷ヒカリエ
申込先：connpass

**Comment by NoriakiHirai** [comment]
受講完了のため、クローズ
